inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.0

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Lint/MissingSuper:
  Exclude:
    - 'spec/mocks/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-post-image-generator.rb'